spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "MicroBank Gateway Service"
    version: "0.0.1-SNAPSHOT"

logging:
  level:
    com:
      microbank:
        gatewayserver: DEBUG