server:
  port: 9000
spring:
  application:
    name: "card"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3306/cardb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: localhost
    port: 5672
    username: local
    password: localpass

management:
  endpoints:
    web:
      exposure:
        include: "*"
#  config:
#    import:
#      - "application_prod.yml"
#      - "application_qa.yml"
#  profile:
#    active:
#      - "qa"
#
#build:
#  version: 0.0.1-LOCAL-SNAPSHOT
#
#account:
#  message: "Welcome to MicroBank Card Service"
#  contactDetails:
#    email: "han@microbank.com"
#    name: "Han Solo"
#  onCallSupport:
#    - (66)23423234
#    - (95)46234456
