services:
  network-deploy-service:
    networks:
      - microbank

  db-service:
    extends:
      service: network-deploy-service
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ms-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"

  ms-configserver-config:
    extends:
      service: ms-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071

  ms-eurekaserver-config:
    extends:
      service: ms-configserver-config
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      SRRING_DATASOURCE_ROOT_USERNAME: "root"
      SPRING_DATASOURCE_ROOT_PASSWORD: "root"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"

