name: "microbank"

services:
  accountdb:
    container_name: "accountdb"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "accountdb"
    extends:
      file: common.yml
      service: db-service

  loandb:
    container_name: "loandb"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "loandb"
    extends:
      file: common.yml
      service: db-service

  cardb:
    container_name: "cardb"
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "cardb"
    extends:
      file: common.yml
      service: db-service

  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    extends:
      file: common.yml
      service: network-deploy-service

  configserver:
    image: "hanlinkhaing/microbank-configserver:0.0.1-SNAPSHOT"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    extends:
      file: common.yml
      service: ms-base-config

  account:
    image: "hanlinkhaing/microbank-account:0.0.1-SNAPSHOT"
    container_name: "account-ms"
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      loandb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "account"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountdb:3306/accountdb"
    extends:
        file: common.yml
        service: ms-configserver-config

  loan:
    image: "hanlinkhaing/microbank-loan:0.0.1-SNAPSHOT"
    container_name: "loan-ms"
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      loandb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loan"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loandb:3306/loandb"
    extends:
      file: common.yml
      service: ms-configserver-config

  card:
    image: "hanlinkhaing/microbank-card:0.0.1-SNAPSHOT"
    container_name: "card-ms"
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
      cardb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "card"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardb:3306/cardb"
    extends:
      file: common.yml
      service: ms-configserver-config

networks:
  microbank:
    driver: "bridge"