server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
        - "application_prod.yml"
        - "application_qa.yml"
    profile:
      active: qa

build:
  version: 0.0.1-LOCAL-SNAPSHOT

account:
  message: "Welcome to MicroBank Loan Service"
  contactDetails:
    email: "han@microbank.com"
    name: "Han Solo"
  onCallSupport:
    - (66)23423234
    - (95)46234456