server:
  port: 8090
spring:
  application:
    name: "loan"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loandb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loan"
    description: "MicroBank Loan Service"
    version: "0.0.1-SNAPSHOT"
#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#  profile:
#    active:
#      - "qa"
#
#build:
#  version: 0.0.1-LOCAL-SNAPSHOT
#
#account:
#  message: "Welcome to MicroBank Loan Service"
#  contactDetails:
#    email: "han@microbank.com"
#    name: "Han Solo"
#  onCallSupport:
#    - (66)23423234
#    - (95)46234456