spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
# Classpath location
          search-locations: "classpath:/config"
# Filesystem location
#          search-locations: "file:///Users//hanlinkhaing//Downloads//Documents//config"

server:
  port: 8071
